[package]
name = "alcl"
version = "0.1.0"
authors = ["akitsu-sanae <akitsu.sanae@gmail.com>"]

[dependencies]
peg = "*"
peg-syntax-ext = "*"
kazuma = { git = "https://github.com/akitsu-sanae/kazuma" }

